# Numpy



#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [82]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [2]:
print(np.__version__)
np.show_config()

1.21.6
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSS

#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [5]:
N=np.array([1,2,3])
print(N.size)
print(N.itemsize)

3
8


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [6]:
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [7]:
N=np.zeros(10)
N[4]=1
print(N)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [9]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [10]:
N=np.arange(51)
N[::-1]

array([50, 49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34,
       33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17,
       16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [11]:
N=np.arange(0,9)
N.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [15]:
N=np.array([1,2,0,0,4,0])
np.nonzero(N)

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [16]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [17]:
np.random.randn(3,3,3)

array([[[ 0.15246605,  1.80146179, -2.24993357],
        [-0.29530638,  0.38598248, -0.12557751],
        [-1.03700412,  0.32950043, -0.43173849]],

       [[ 0.33457696, -2.1752658 , -0.16792339],
        [ 1.86197159, -0.7055692 ,  0.67547069],
        [ 1.1434685 ,  0.39160564, -0.10930765]],

       [[ 0.79141863,  0.89359379, -0.6733162 ],
        [ 1.13822102,  0.08076512, -0.34681487],
        [ 0.5812033 , -0.8563351 ,  0.25756721]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [19]:
N=np.random.randn(10,10)
A=N.max()
B=N.min()
print(A,B)

3.239849492850939 -2.5612353521923032


#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [23]:
N=np.arange(0,31)
N.mean()

15.0

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [26]:
N=np.ones((5,5))
N[1:4,1:4]=0
print(N)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [28]:
N=np.ones((5,5))
N=np.pad(N,pad_width=1,mode='constant',constant_values=0)
print(N)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [29]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [31]:
N=np.diag(1+np.arange(4),k=-1)
print(N)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [32]:
N=np.zeros((8,8))
N[1::2,::2]=1
N[::2,1::2]=1
print(N)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [36]:
np.unravel_index(100,(6,7,8))

(1, 5, 4)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [34]:
np.tile(np.array([[0,1],[1,0]]),(4,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [37]:
x=np.random.randn(5,5)
xmax,xmin=x.max(),x.min()
x=(x-xmin)/(xmax-xmin)
print(x)

[[0.0375976  0.21866619 0.82974584 0.05458481 0.24014218]
 [0.39623863 0.52019821 0.22567692 0.79559006 0.54168537]
 [0.85351648 0.15554452 0.28266408 0.39171602 0.63832379]
 [0.43921598 0.26204359 0.80988482 0.48502892 1.        ]
 [0.49167229 0.40170253 0.50461493 0.08120199 0.        ]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [38]:
RGBA = np.dtype([('red',np.uint8),('green',np.uint8),('blue',np.uint8),('alpha',np.uint8)])
color = np.array((1,2,4,3),dtype = RGBA)
print(color['red'])
type(color)

1


numpy.ndarray

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [39]:
x=np.random.randn(5,3)
y=np.random.randn(3,2)
print(x @ y)
np.dot(x,y)

[[-0.35719052 -1.40166926]
 [ 2.73985571  1.23612457]
 [ 1.86024147  1.50447805]
 [-2.57424615 -2.66500183]
 [ 1.22848372  0.15672253]]


array([[-0.35719052, -1.40166926],
       [ 2.73985571,  1.23612457],
       [ 1.86024147,  1.50447805],
       [-2.57424615, -2.66500183],
       [ 1.22848372,  0.15672253]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [40]:
x=np.random.randn(5,3)
y=np.random.randn(3,2)
print(x @ y)
np.dot(x,y)

[[-1.51372076  0.08559911]
 [ 0.5292589   0.36170056]
 [ 0.91870553  0.82304699]
 [ 0.82421067  0.0279875 ]
 [-0.88097889  0.30507482]]


array([[-1.51372076,  0.08559911],
       [ 0.5292589 ,  0.36170056],
       [ 0.91870553,  0.82304699],
       [ 0.82421067,  0.0279875 ],
       [-0.88097889,  0.30507482]])

#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [41]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [42]:
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z

NameError: ignored

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [43]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


array([-9.22337204e+18])

#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [44]:
N=np.random.randn(5,5)
print(N)
n=np.round(N,2)
print(N)

[[ 1.33569515  1.961632   -0.89936595  0.05090688 -0.24654489]
 [ 0.65099259  0.15751962 -0.88435809 -1.35524742 -0.51450026]
 [-1.15869246 -0.12092277 -2.10649722  0.41432799  0.54495702]
 [-0.52390238 -1.03160014 -1.21142479 -0.23524792 -0.20361216]
 [-2.1888062  -0.29152836 -0.11906377 -0.51035227  1.87373775]]
[[ 1.33569515  1.961632   -0.89936595  0.05090688 -0.24654489]
 [ 0.65099259  0.15751962 -0.88435809 -1.35524742 -0.51450026]
 [-1.15869246 -0.12092277 -2.10649722  0.41432799  0.54495702]
 [-0.52390238 -1.03160014 -1.21142479 -0.23524792 -0.20361216]
 [-2.1888062  -0.29152836 -0.11906377 -0.51035227  1.87373775]]


#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [45]:
N=np.array([5,10,15,20])
M=np.array([15,20,25,30])
np.intersect1d(N,M)

array([15, 20])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

In [46]:
np.random.randn(1000).reshape(10,10,10)*np.nan
np.seterr(all='ignore')

{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}

#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [47]:
np.sqrt(-1) == np.emath.sqrt(-1)

False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [48]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print(yesterday)
print(today)
print(tomorrow)

2022-11-18
2022-11-19
2022-11-20


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [49]:
date= np.arange('2016-07','2016-08', dtype='datetime64[D]')
print(date)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [50]:
A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [51]:
A = np.random.uniform(0,10,10)

print (A-A%1)
print (np.floor(A))
print (np.ceil(A)-1)
print (A.astype(int))
print (np.trunc(A))

[9. 6. 5. 2. 8. 8. 1. 6. 3. 6.]
[9. 6. 5. 2. 8. 8. 1. 6. 3. 6.]
[9. 6. 5. 2. 8. 8. 1. 6. 3. 6.]
[9 6 5 2 8 8 1 6 3 6]
[9. 6. 5. 2. 8. 8. 1. 6. 3. 6.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [52]:
a=np.zeros((5,5))
a+=np.arange(5)
print(a)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [53]:
def generate():
    for x in range(10):
        yield x
N = np.fromiter(generate(),dtype=float,count=-1)
print(N)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [54]:
np.linspace(0,1,11,endpoint=False)[1:]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [ ]:
a=np.random.randn(10)
a.sort()
print(a)

#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [56]:
N=np.arange(10)
np.add.reduce(N)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [57]:
a=np.random.randint(0,10)
b=np.random.randint(0,10)
equal=np.allclose(a,b)
print(equal)
equal=np.array_equal(a,b)
print(equal)

False
False


#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [58]:
N=np.zeros(10)
N.flags.writeable = False
print(N)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [59]:
N= np.random.randint(0,9,(10,2))
x,y = N[:,0], N[:,1]
r = np.sqrt(x**2+y**2)
t = np.arctan2(y,x)
poles = np.c_[r,t]
print(poles)

[[11.3137085   0.78539816]
 [ 7.07106781  0.78539816]
 [ 6.70820393  1.10714872]
 [ 6.40312424  0.89605538]
 [ 6.40312424  0.89605538]
 [10.63014581  0.71883   ]
 [ 8.24621125  1.32581766]
 [10.          0.92729522]
 [ 5.65685425  0.78539816]
 [ 2.23606798  0.46364761]]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [61]:
N=np.random.rand(10)
N[N.argmax()]=0
print(N)

[0.42660713 0.36915724 0.70878855 0.37471732 0.48048614 0.16905514
 0.6840666  0.27740701 0.         0.11510037]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

In [62]:
N = np.zeros((5,5), [('x',float),('y',float)])
N['x'], N['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(N)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [63]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.163637117973


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [64]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [65]:
np.set_printoptions(threshold=float("inf"))
N = np.zeros((16,16))
print(N)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [67]:
N = np.arange(100)
A = np.random.uniform(0,100)
index = (np.abs(N-A)).argmin()
print(N[index])

72


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

In [69]:
N = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(N)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  """


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

In [70]:
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)
import scipy

import scipy.spatial

Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

[[0.         0.58329027 0.69294689 0.20118175 0.87023425 0.71880062
  0.3855992  0.5205526  0.84968915 0.74682295]
 [0.58329027 0.         0.43309476 0.755615   0.34544934 0.13596844
  0.20961421 0.34178237 0.74533598 0.19126341]
 [0.69294689 0.43309476 0.         0.77201194 0.35636751 0.47727192
  0.51357267 0.74298932 0.3180794  0.57734573]
 [0.20118175 0.755615   0.77201194 0.         1.00818406 0.89133728
  0.57174089 0.72173177 0.85559868 0.93028405]
 [0.87023425 0.34544934 0.35636751 1.00818406 0.         0.27288892
  0.54094411 0.67698442 0.64100135 0.35896287]
 [0.71880062 0.13596844 0.47727192 0.89133728 0.27288892 0.
  0.34013246 0.41353599 0.79525793 0.10147051]
 [0.3855992  0.20961421 0.51357267 0.57174089 0.54094411 0.34013246
  0.         0.24939924 0.78858057 0.36122824]
 [0.5205526  0.34178237 0.74298932 0.72173177 0.67698442 0.41353599
  0.24939924 0.         1.03263509 0.36770891]
 [0.84968915 0.74533598 0.3180794  0.85559868 0.64100135 0.79525793
  0.78858057 1.03263

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [71]:
N = np.arange(10, dtype=np.float32)
N = N.astype(np.int32, copy=False)
print(N)

[0 1 2 3 4 5 6 7 8 9]


#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [72]:
from io import StringIO

s = StringIO("""1, 2, 3, 4, 5\n
                6,  ,  , 7, 8\n
                 ,  , 9,10,11\n""")
N = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(N)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [73]:
N = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(N):
    print(index, value)
for index in np.ndindex(N.shape):
    print(index, N[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

In [74]:
sigma,myu = 1.0,0.0

X,Y  = np.meshgrid(np.linspace(-1,1,10),np.linspace(-1,1,10))
D = np.sqrt(X**2+Y**2)
N = np.exp(-(D-myu)**2/(2*sigma**2))
print(N)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [75]:
n = 10
p = 3
N = np.zeros((n,n))
np.put(N, np.random.choice(range(n*n), p, replace=False),1)
print(N)

np.put(N,11,1)
print(N)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [77]:
X = np.random.rand(5, 10)
Y = X - X.mean(axis = 1,keepdims = True)
print(Y)
X.mean(axis = 1).reshape(-1,1) == X.mean(axis = 1,keepdims =True)

[[-0.35072383 -0.14243448  0.51356937 -0.0123777   0.23689194 -0.11645385
   0.17049359 -0.11595112  0.01981702 -0.20283094]
 [ 0.00239114 -0.18058407 -0.0994147   0.23982529  0.28985286 -0.27004349
  -0.16965519  0.30024899 -0.0815182  -0.03110263]
 [-0.10247517 -0.13472338  0.17587208  0.05330361  0.14996862  0.44882295
   0.19689488 -0.17349716 -0.13863644 -0.47552999]
 [ 0.54039404 -0.28295662 -0.31661294  0.00669612 -0.32167087  0.5300476
  -0.25929699  0.20804027 -0.35081887  0.24617826]
 [ 0.31391819 -0.60029452  0.10323511  0.24288004  0.11383873 -0.13926304
   0.30528426  0.18301144 -0.61773564  0.09512543]]


array([[ True],
       [ True],
       [ True],
       [ True],
       [ True]])

#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [78]:
N = np.random.randint(0,10,(5,5))
print(Z)

print(N[(-N)[:,1].argsort()])
print(N[:,N[1,:].argsort()])

[[0.61528352 0.55159516]
 [0.49779536 0.44308841]
 [0.77861929 0.33332926]
 [0.9124156  0.39827107]
 [0.72031609 0.32011112]
 [0.55988401 0.20466791]
 [0.36562926 0.14731957]
 [0.82456712 0.41540191]
 [0.82278509 0.47816498]
 [0.18801618 0.59332274]]
[[3 7 9 7 9]
 [6 4 5 6 3]
 [8 3 6 8 2]
 [8 3 8 9 9]
 [4 0 6 4 5]]
[[2 3 6 8 8]
 [3 4 5 6 6]
 [9 7 9 3 7]
 [9 3 8 8 9]
 [5 0 6 4 4]]


#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [79]:
N = np.random.randint(0,3,(3,10))
N[:,1] = 0
N = N.astype(bool)
print(N)
print(~N)
(N).any(axis = 0)

[[False False  True  True  True  True False False  True False]
 [ True False  True  True  True False False  True  True  True]
 [ True False False  True False  True  True  True False False]]
[[ True  True False False False False  True  True False  True]
 [False  True False False False  True  True False False False]
 [False  True  True False  True False False False  True  True]]


array([ True, False,  True,  True,  True,  True,  True,  True,  True,
        True])

#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [81]:
N=np.array([8,7,1,5,3,4])
difN=np.absolute(N-2)
index=difN.argmin()
print(N[index])
print(index)

1
2


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

In [83]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

In [84]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

N = NamedArray(np.arange(10), "range_10")
print (N.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

In [87]:
N = np.ones(10)
I = np.random.randint(0,len(N),20)
N += np.bincount(I, minlength=len(N))
print(N)
np.add.at(N, I, 1)
print(N)

[4. 4. 6. 1. 3. 4. 2. 2. 3. 1.]
[ 7.  7. 11.  1.  5.  7.  3.  3.  5.  1.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

In [88]:
N = [1,2,3,4,5,6]
A = [1,3,9,3,4,1]
B = np.bincount(A,N)
print(B)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

In [94]:
 x, y = 256, 256
D = np.random.randint(0, 4, (y, x, 3)).astype(np.ubyte)
colors = np.unique(D.reshape(-1, 3), axis=0)
N = len(colors)
print(N)

x, y = 256, 256
D = np.random.randint(0,4,(y,x,3), dtype=np.uint8)

D24 = np.dot(D.astype(np.uint32),[1,256,65536])

N = len(np.unique(D24))
print(N)

64
64


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

In [95]:
N = np.random.randint(0,10,(3,4,3,4)) 
sum = N.sum(axis=(-2,-1))
print(sum)
sum = N.reshape(N.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[52 47 61 45]
 [56 47 65 50]
 [65 67 68 49]]
[[52 47 61 45]
 [56 47 65 50]
 [65 67 68 49]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

In [96]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)
import pandas as pd
print(pd.Series(D).groupby(S).mean())

[0.46689419 0.59498587 0.57815794 0.46561214 0.54512541 0.6691957
 0.39800923 0.58577353 0.41796027 0.55385755]
0    0.466894
1    0.594986
2    0.578158
3    0.465612
4    0.545125
5    0.669196
6    0.398009
7    0.585774
8    0.417960
9    0.553858
dtype: float64


#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [97]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

np.diag(np.dot(A, B)) #Slow

np.sum(A * B.T, axis=1) #Fast

np.einsum("ij,ji->i", A, B) #Faster

array([1.1411624 , 0.81450414, 2.27203408, 1.00580553, 1.71696991])

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

In [100]:
N = np.array([1,2,3,4,5])
nz = 3
N0 = np.zeros(len(N) + (len(N)-1)*(nz))
N0[::nz+1] = N
print(N0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [101]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [102]:
N = np.arange(25).reshape(5,5)
N[[0,1]] = N[[1,0]]
print(N)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

In [103]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 1, 46) ( 1, 59) ( 4, 23) ( 4, 24) ( 6, 38) ( 6, 97) ( 7, 57) ( 7, 95)
 (23, 24) (23, 36) (23, 86) (27, 79) (27, 90) (33, 62) (33, 86) (36, 86)
 (38, 97) (40, 64) (40, 95) (46, 50) (46, 59) (46, 99) (50, 61) (50, 68)
 (50, 99) (57, 95) (61, 68) (62, 86) (64, 95) (79, 90)]


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

In [105]:
N = np.bincount([1,1,2,3,4,4,6])
D = np.repeat(np.arange(len(N)), N)
print(D)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

In [108]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
N = np.arange(20)
print(moving_average(N, n=3))

from numpy.lib.stride_tricks import sliding_window_view

N = np.arange(20)
print(sliding_window_view(N, window_shape=3).mean(axis=-1))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

In [109]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.strides[0], a.strides[0])
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
N = rolling(np.arange(10), 3)
print(N)

N = np.arange(10)
print(sliding_window_view(N, window_shape=3))

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]
[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

In [110]:
N = np.random.randint(0,2,100)
np.logical_not(N, out=N)

N = np.random.uniform(-1.0,1.0,100)
np.negative(N, out=N)

array([ 0.64690749, -0.49860537,  0.46109184, -0.46713982, -0.79413428,
        0.03936891,  0.62818881, -0.96307777,  0.89037784, -0.95764669,
        0.06171124, -0.40093156,  0.59980451,  0.40484983, -0.81455169,
       -0.21930288,  0.05542451,  0.61997056, -0.16592821, -0.61450083,
        0.40740135, -0.06411088, -0.97608065, -0.09224307,  0.92390491,
        0.83912621,  0.58061832, -0.97321205,  0.58505022,  0.82931029,
        0.36603059,  0.45658069, -0.38541076, -0.98667016,  0.93030278,
       -0.72506659,  0.78778445,  0.00581007,  0.70422149, -0.11978036,
       -0.64651537, -0.2641632 ,  0.90606268,  0.10789292, -0.46533567,
       -0.07994418, -0.29127131,  0.3340587 , -0.69722969, -0.19907889,
       -0.73305784,  0.31653092, -0.25144436,  0.84969434, -0.68125284,
        0.98779463,  0.67139959, -0.31053264, -0.52062244, -0.31195783,
        0.46241215,  0.83251726,  0.0870355 ,  0.47451322,  0.53594298,
        0.68301483,  0.5417876 ,  0.46670055,  0.01135863,  0.71

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

In [111]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[ 3.21222095  1.0111218  10.66221347  5.4873207   3.50527087 11.8307165
  5.1894028  10.05485778  4.49748998  4.33584324]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

In [112]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 6.85634884  9.15046957  9.6500156  13.26457153 10.54512433  1.01083816
  15.98756315 13.91451371 17.00783468 11.39805895]
 [ 0.20645981  3.28435201  3.17637748  6.20066911  9.9506713   8.54505768
   3.90522213  7.33540055  4.13676166  2.861978  ]
 [ 2.31744557  6.54797321  7.33023491  8.04266193 15.17481222 15.94144208
   2.76537724  9.49147454  0.1701239   4.55799241]
 [ 9.12140002 10.69318356  9.72281183  3.1507754   2.11038491  7.43678651
   1.57568977  1.98718031  2.23968277  4.9831145 ]
 [ 5.70381592 10.92681421 10.68719029  0.11174415  7.04160447 12.10693263
   1.86606227  1.4560888   3.33470482  0.06458222]
 [ 5.03358945 11.30251376 11.25260975  0.73324273  8.23902754 13.49993541
   3.02165038  2.13444286  3.93339436  1.36340089]
 [ 3.15322164  4.39481237  3.75701805  2.91900883  6.03881054  5.89237781
   5.33615367  3.96302418  3.65347575  5.81461736]
 [ 9.72878483 11.77049387 10.82766296  3.79272919  2.01526913  8.22504894
   0.55728586  2.58864828  3.34725935  4.28556632]


#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

In [114]:
N = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=N.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Ns = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
N_start = (P-Rs//2)
N_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(N_start,0)).tolist()
N_start = (np.maximum(N_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(N_stop-Ns,0))).tolist()
N_stop = (np.minimum(N_stop,Ns)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(N_start,N_stop)]
R[r] = N[z]
print(N)
print(R)

[[8 1 0 6 4 4 9 6 3 9]
 [9 5 7 0 4 2 1 4 1 9]
 [3 4 0 3 7 5 0 2 8 2]
 [6 1 4 2 6 3 8 1 4 0]
 [8 8 9 7 8 7 1 0 3 0]
 [2 5 9 5 3 6 7 7 3 6]
 [4 0 8 4 0 0 1 1 4 4]
 [2 0 8 9 4 3 2 4 5 5]
 [1 8 3 0 0 7 3 2 8 2]
 [7 0 2 0 5 6 3 4 2 9]]
[[0 0 0 0 0]
 [0 8 1 0 6]
 [0 9 5 7 0]
 [0 3 4 0 3]
 [0 6 1 4 2]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:23: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.


#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [118]:
N = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(N,(11,4),(4,4))
print(R)
N = np.arange(1, 15, dtype=np.uint32)
print(sliding_window_view(N, window_shape=4))

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]
[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

In [119]:
N = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(N) 
rank = np.sum(S > 1e-10)
print(rank)

rank = np.linalg.matrix_rank(N)
print(rank)

10
10


#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

In [120]:
N = np.random.randint(0,10,50)
print(np.bincount(N).argmax())

0


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [122]:
N = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (N.shape[0]-3)
j = 1 + (N.shape[1]-3)
C = stride_tricks.as_strided(N, shape=(i, j, n, n), strides=N.strides + N.strides)
print(C)
N = np.random.randint(0,5,(10,10))
print(sliding_window_view(N, window_shape=(3, 3)))

[[[[0 0 1]
   [0 4 0]
   [1 1 0]]

  [[0 1 0]
   [4 0 0]
   [1 0 4]]

  [[1 0 1]
   [0 0 4]
   [0 4 4]]

  [[0 1 0]
   [0 4 3]
   [4 4 1]]

  [[1 0 1]
   [4 3 0]
   [4 1 2]]

  [[0 1 3]
   [3 0 4]
   [1 2 2]]

  [[1 3 4]
   [0 4 1]
   [2 2 1]]

  [[3 4 2]
   [4 1 2]
   [2 1 2]]]


 [[[0 4 0]
   [1 1 0]
   [0 4 0]]

  [[4 0 0]
   [1 0 4]
   [4 0 0]]

  [[0 0 4]
   [0 4 4]
   [0 0 0]]

  [[0 4 3]
   [4 4 1]
   [0 0 4]]

  [[4 3 0]
   [4 1 2]
   [0 4 3]]

  [[3 0 4]
   [1 2 2]
   [4 3 0]]

  [[0 4 1]
   [2 2 1]
   [3 0 4]]

  [[4 1 2]
   [2 1 2]
   [0 4 0]]]


 [[[1 1 0]
   [0 4 0]
   [3 2 0]]

  [[1 0 4]
   [4 0 0]
   [2 0 4]]

  [[0 4 4]
   [0 0 0]
   [0 4 3]]

  [[4 4 1]
   [0 0 4]
   [4 3 3]]

  [[4 1 2]
   [0 4 3]
   [3 3 4]]

  [[1 2 2]
   [4 3 0]
   [3 4 0]]

  [[2 2 1]
   [3 0 4]
   [4 0 2]]

  [[2 1 2]
   [0 4 0]
   [0 2 3]]]


 [[[0 4 0]
   [3 2 0]
   [0 0 0]]

  [[4 0 0]
   [2 0 4]
   [0 0 2]]

  [[0 0 0]
   [0 4 3]
   [0 2 1]]

  [[0 0 4]
   [4 3 3]
   [2 1 4]]

  [[0 4 3]
   

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

In [123]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 5  8  5 12 15]
 [ 8  6 17  8 13]
 [ 5 17  2 42  6]
 [12  8 42  5 11]
 [15 13  6 11  1]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

In [124]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

In [125]:
N = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(N, np.arange(0, N.shape[0], k), axis=0),
                                       np.arange(0, N.shape[1], k), axis=1)
print(S)
N = np.ones((16,16))
k = 4
windows = np.lib.stride_tricks.sliding_window_view(N, (k, k))
S = windows[::k, ::k, ...].sum(axis=(-2, -1))
N = np.ones((16, 16))
k = 4
print(sliding_window_view(N, window_shape=(k, k))[::k, ::k].sum(axis=(-2, -1)))

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]
[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [128]:
def iterate(Z):
    # Count neighbours
    D = (N[0:-2,0:-2] + N[0:-2,1:-1] + N[0:-2,2:] +
         N[1:-1,0:-2]                + N[1:-1,2:] +
         N[2:  ,0:-2] + N[2:  ,1:-1] + N[2:  ,2:])

    # Apply rules
    birth = (D==3) & (N[1:-1,1:-1]==0)
    survive = ((D==2) | (D==3)) & (N[1:-1,1:-1]==1)
    N[...] = 0
    N[1:-1,1:-1][birth | survive] = 1
    return N

N = np.random.randint(0,2,(50,50))
for i in range(100): N = iterate(N)
print(N)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 1 1 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 1 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 1 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 1 1 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 1 1 1 1 1 1 0 0 0 0 0 0

#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

In [130]:
N = np.arange(10000)
np.random.shuffle(N)
n = 5

print (N[np.argsort(N)[-n:]]) # Slow

print (N[np.argpartition(-N,n)[:n]]) # Fast

[9995 9996 9997 9998 9999]
[9998 9997 9999 9996 9995]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

In [131]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

In [133]:
N = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(N.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

In [135]:
x = np.random.rand(int(5e7))

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

3.98 s ± 320 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
144 ms ± 905 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
124 ms ± 830 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

In [136]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[0 2 4]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [137]:
Z = np.random.randint(0,5,(10,3))
print(Z)

E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)

U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)

[[0 4 3]
 [3 1 3]
 [1 1 2]
 [1 2 4]
 [4 3 1]
 [0 1 4]
 [3 2 4]
 [2 4 1]
 [1 4 2]
 [4 3 0]]
[[0 4 3]
 [3 1 3]
 [1 1 2]
 [1 2 4]
 [4 3 1]
 [0 1 4]
 [3 2 4]
 [2 4 1]
 [1 4 2]
 [4 3 0]]
[[0 4 3]
 [3 1 3]
 [1 1 2]
 [1 2 4]
 [4 3 1]
 [0 1 4]
 [3 2 4]
 [2 4 1]
 [1 4 2]
 [4 3 0]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

In [138]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

In [139]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)
uZ = np.unique(Z, axis=0)
print(uZ)

[[0 1 0]
 [0 1 1]
 [1 0 0]
 [1 0 1]
 [1 1 1]]
[[0 1 0]
 [0 1 1]
 [1 0 0]
 [1 0 1]
 [1 1 1]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

In [140]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       # np.sum(A)
np.einsum('i,i->i', A, B) # A * B
np.einsum('i,i', A, B)    # np.inner(A, B)
np.einsum('i,j->ij', A, B)    # np.outer(A, B)

array([[0.38749371, 0.42774202, 0.11310002, 0.55714244, 0.74857294,
        0.90844168, 0.04943907, 0.88239192, 0.07248123, 0.70179296],
       [0.35928848, 0.39660716, 0.1048676 , 0.51658867, 0.69408517,
        0.84231724, 0.04584045, 0.81816362, 0.0672054 , 0.65071024],
       [0.32547911, 0.35928607, 0.09499946, 0.46797721, 0.62877113,
        0.76305443, 0.04152683, 0.74117369, 0.06088131, 0.58947782],
       [0.22025761, 0.24313539, 0.06428786, 0.31668866, 0.42550081,
        0.51637275, 0.02810196, 0.50156566, 0.04119949, 0.39891032],
       [0.03712441, 0.04098046, 0.01083572, 0.05337786, 0.07171814,
        0.0870346 , 0.00473658, 0.08453887, 0.00694417, 0.06723631],
       [0.32890834, 0.36307149, 0.09600037, 0.4729078 , 0.63539583,
        0.77109394, 0.04196435, 0.74898265, 0.06152276, 0.59568853],
       [0.17090878, 0.18866078, 0.04988413, 0.2457344 , 0.33016714,
        0.40067918, 0.0218057 , 0.38918962, 0.03196872, 0.30953426],
       [0.15694516, 0.17324678, 0.0458084

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

In [141]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5  
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                 
r_int = np.linspace(0, r.max(), 200)   
x_int = np.interp(r_int, r, x)        
y_int = np.interp(r_int, r, y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

In [142]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)

In [143]:
X = np.random.randn(100) 
N = 1000 
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-3.91961424e-01  2.39321012e-04]
